### ISSUE TITLE
feature request: Retain cursor position when entering indirect editing

### ISSUE THREAD

**Issue by terlar** [twlz0ne/separedit.el#11]
I find that many times I navigate to the place I want to edit within the string, before entering the string edit mode. Then I have to navigate once again when entering separedit.

It would be nice if an option was available to retain the cursor position you had when you requested separedit. So if the indirect buffer could put the cursor at the same place you had within the string when it opens.

For example (where `|` is representing the cursor position).

Original buffer:
```
emacsInit = writeText "init.el" ''
  (set-face-attribute 'default nil :height 150)
  (scroll-bar-mode 0)
  (tool-bar-mode 0)

  (mes|sage "%s" "hello")
'';
```

Separedit buffer:
```

(set-face-attribute 'default nil :height 150)
(scroll-bar-mode 0)
(tool-bar-mode 0)

(mes|sage "%s" "hello")

```

**Comment by twlz0ne** [comment]
I probably have a solution.

But wait for me for a while, I'm working on another feature:

![Screenshot_2020-03-05_at_4 43 20_PM_separedit-help-buffer-variable](https://user-images.githubusercontent.com/2653486/77248545-37b7fe80-6c75-11ea-878e-1a78e2ac3635.png)

**Comment by terlar** [comment]
Nice, works well, thank you :tada:
