### ISSUE TITLE
Respect source-buffer's `fill-column` value

### ISSUE THREAD

**Issue by j-cr** [twlz0ne/separedit.el#18]
The problem: when calling `fill-region` or `fill-paragraph`, or using `auto-fill-mode` in the indirect edit buffer, the indentation level in the source buffer isn't taken in the account. Thus the text in the source buffer ends up exceeding the `fill-column` margin even if `fill-*` functions are used in the edit buffer to format the text.

Example indirect buffer (org-mode, fill-column = 80):
```
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.
```

Resulting source buffer (note the comment is exceeding the 80 characters width):
```
(defun foo ()
  ;; Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
  ;; incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis
  ;; nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  ;; consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
  ;; dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
  ;; sunt in culpa qui officia deserunt mollit anim id est laborum.
  (foo bar baz))
```

**Comment by twlz0ne** [comment]
Checkout [REAME#Continue fill-column width in edit buffer](https://github.com/twlz0ne/separedit.el#continue-fill-column-width-in-edit-buffer).

**Comment by j-cr** [comment]
Ah, somehow I missed that; sorry!
