### ISSUE TITLE
Extra trailing space on empty line

### ISSUE THREAD

**Issue by feng-qi** [twlz0ne/separedit.el#27]
When there's empty line in a comment block, separedit it and `separedit-commit` it, a trailing space will be appended to this line.

For example:

![image](https://user-images.githubusercontent.com/3600573/143415993-008745c1-4056-45fa-8b04-f94cae57ec62.png)

This picture shows that a trailing space is added to line 2 after `separedit-commit`. Shown in red when `show-trailing-whitespace` is `t`. You can try to reproduce with these code snippets:

c/c++:
```c
/*
 * Summary:
 *
 *   1. item 1
 *   2. item 2
 */
```
emacs lisp:
```emacs-lisp
;; (defvar bootstrap-version)
;;
;; (let ((bootstrap-file
;;        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
;;       (bootstrap-version 5))
;;   (unless (file-exists-p bootstrap-file)
;;     (with-current-buffer
;;         (url-retrieve-synchronously
;;          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
;;          'silent 'inhibit-cookies)
;;       (goto-char (point-max))
;;       (eval-print-last-sexp)))
;;   (load bootstrap-file nil 'nomessage))
```

**Comment by twlz0ne** [comment]
```elisp
(setq separedit-remove-trailing-spaces-in-comment t)
```

**Comment by feng-qi** [comment]
It works. Thanks. I didn't know that before.
