### ISSUE TITLE
`(separedit--point-at-comment)` does not correctly identify comments when `tree-sitter-hl-mode` is enabled

### ISSUE THREAD

**Issue by elizagamedev** [twlz0ne/separedit.el#31]
[tree-sitter](https://emacs-tree-sitter.github.io/) replaces the major mode's syntax highlighting its own doc/comment faces when `tree-sitter-hl-mode` is enabled. These faces are `tree-sitter-hl-face:doc` and `tree-sitter-hl-face:comment`. Two solutions I can see to fix this issue:

1. Append these to `separedit-comment-faces`.
2. Have `(separedit--point-at-comment)` check for faces which inherit from `font-lock-doc-face` etc, rather than checking for equality. The tree sitter faces do inherit from the semantically correct font lock faces, and I'm sure this would correct other edge-cases like this in the future.

**Comment by twlz0ne** [comment]
Thanks for your advice.
