### ISSUE TITLE
Docstrings don't unescape and remove quotes

### ISSUE THREAD

**Issue by andreyorst** [twlz0ne/separedit.el#32]
Possible duplicate of #29, ut not sure, as this involves strings specifically.

I've just noticed that this happens to the docstrings in various Lisp modes, like the `emacs-lisp-mode`, `fennel-mode`, `clojure-mode`, e.t.c. Previously when I've invoked the `separedit-dwim` on the docstring it used the `markdown-mode`, same as for comments, but without the double quotes and everything was correctly unescaped. Now it's just narrowing to the whole string, delimiters included. Here's a simple repro:

```emacs-lisp
(defun f ()
  "Some docstring"
  nil)
```

Invoking `separedit-dwim` on the docstring opens the following buffer:

```markdown
"Some docstring"
```

The majori mode is correctly set to `markdown-mode` but the delimiters are still present.

If I edit an ordinary string, like here:

```emacs-lisp
(defun f ()
  nil
  "Some docstring")
```

The buffer opens without delimiters in the `separedit-double-quote-string-mode`:

```
Some docstring
````

I wish I could still have the double-quotes removed in docstrings, and the inserted double-quotes correctly re-escaped on exit. It makes editing docstrings much less painful, and allows editing example code enclosed in markdown code blocks embedded in the docstring.

**Comment by twlz0ne** [comment]
Maybe some packages conflict with separedit.

What do you get when you execute `separedit--block-info` on a string?

Is the result of the following script what you expect?

```sh
⋊> emacs -Q --eval "(progn
                      (toggle-debug-on-error)
                      (require 'seq)
                      (setq user-emacs-directory
                            (car (seq-filter
                                  #'file-exists-p
                                  (list (format \"~/.emacs.d/%s/\" emacs-version)
                                        (format \"~/.emacs.d/%s/\" emacs-major-version)
                                        \"~/.emacs.d/\"))))
                      (setq package-user-dir (concat user-emacs-directory \"elpa/\"))
                      (package-initialize)
                      (require 'markdown-mode)
                      (require 'separedit)
                      (setq separedit-default-mode 'markdown-mode)
                      (switch-to-buffer \"*.el\")
                      (emacs-lisp-mode)
                      (save-excursion
                        (insert \"(defun f ()\n\"
                                \"  \\\"Some docstring\\\"\n\"
                                \"  nil)\"))
                      (re-search-forward \"Some\" nil t)
                      (separedit-dwim))" -nw
```

![image](https://user-images.githubusercontent.com/2653486/171775284-69899b18-78b4-4206-9636-43b66ee28e96.png)

**Comment by andreyorst** [comment]
I've figured out what's causing the issue.

In my config I set the docstring face to inherit from the comment face (because that's how I like it), and it seems that this affects separedit into thinking that the docstring is a comment. This has an unintended result of correctly applying `markdown-mode` but not removing or unescaping any delimiters. However, IIRC, this wasn't the case some time ago, as it worked correctly for me with the comment face inheritance:

![image](https://user-images.githubusercontent.com/19470159/171994187-b58ecd6e-cef7-4c86-ba97-38f45f6f0442.png)


> What do you get when you execute `separedit--block-info` on a string?

On the docstring:

    (:beginning 36529 :end 36697 :lang-mode nil :string-quotes nil :indent-line1 t :indent-length 4)

Ordinary string:

    (:beginning 36535 :end 36697 :lang-mode nil :string-quotes #("\"" 0 1 (face font-lock-string-face fontified t)) :indent-line1 nil :indent-length 5)

**Comment by twlz0ne** [comment]
It's caused by this commit: https://github.com/twlz0ne/separedit.el/commit/454c9a3561acca3d57cce6ddb356f686b3d8cbee

I'll fix it later. Until then you can use the following advice:

``` elisp
(define-advice separedit--point-at-comment (:around (&rest args) check-non-string)
  (unless (apply 'separedit--point-at-string (cdr args))
    (apply args)))
```
