### ISSUE TITLE
Python comment editing issues

### ISSUE THREAD

**Issue by indigoviolet** [twlz0ne/separedit.el#33]
See gif below for demo of these issues. 

1. Separedit on an indented comment in `python-mode` does not pick up the entire comment : it breaks on blank lines. How can I change this? Or is it a bug? In the gif below, it is the second set of edits ("Hello2... World2"). 

2. Editing indented comments leads to some weird spacing changes in the comment line's indentation (Empty commented lines get indented incorrectly after separedit)

3. With `separedit-leave-blank-line-in-comment t`, the commented blank lines disappear. This seems opposite to the name of the variable.

![separedit-bug](https://user-images.githubusercontent.com/114010/179160246-dce81214-291b-4b77-821b-e8e02d4de578.gif)

**Comment by twlz0ne** [comment]
1 & 2 are the same issue and should be fixed by latest commit.

> 3\. With `separedit-leave-blank-line-in-comment t`, the commented blank lines disappear. This seems opposite to the name of the variable.

`separedit-leave-blank-line-in-comment t` means leave blank lines in source file, don't pad the comment char on the left:

    +---------------+       +---------------+         +---------------+
    | # hello       | Edit  | hello         | Commit  | # hello       |
    |               |------>|               |-------->|               |
    | # word        | C-c ' | word          | C-c C-c | # word        |
    +---------------+       +---------------+         +---------------+

`separedit-leave-blank-line-in-comment nil`:

    +---------------+       +---------------+         +---------------+
    | # hello       | Edit  | hello         | Commit  | # hello       |
    |               |------>|               |-------->| #             |
    | # word        | C-c ' | word          | C-c C-c | # word        |
    +---------------+       +---------------+         +---------------+

Is there an opposite? My English is bad.

**Comment by indigoviolet** [comment]
@twlz0ne, Thank you for the quick fix and this package!

Re: `separedit-leave-blank-line-in-comment`: your diagram helped me understand what it does: as you explained, If you start with blank lines in the region being edited, those lines will not get comment padded. 

A couple of notes regarding this:

1. Since blank lines would normally bound the region being edited,  you would either have to deliberately combine regions (eg. https://github.com/twlz0ne/separedit.el#combine-multipe-adjacent-blocks-as-a-single-edit-block) or select a region containing blank lines, and call separedit on that region. 

2. However, I do think it's a bug that if you start with en empty commented line, that line will lose its comment character:  

```
+---------------+       +---------------+         +---------------+
| # hello       | Edit  | hello         | Commit  | # hello       |
| #             |------>|               |-------->|               |
| # word        | C-c ' | word          | C-c C-c | # word        |
+---------------+       +---------------+         +---------------+
```

3. It's a difficult behavior to name concisely. My alternative suggestion is `separedit-comment-blank-lines`, set to `t` by default.
