### ISSUE TITLE
Editing a string in nix-mode including `${` terminates string early

### ISSUE THREAD

**Issue by terlar** [twlz0ne/separedit.el#9]
In `nix-mode` I was editing a string like this:
```
{
    preBuild = ''
      makeFlagsArray=(
        prefix="$out/share"
        ORG_ADD_CONTRIB="org* ox*"
        GITVERSION="${version}"
        ORGVERSION="${version}"
      );
    '';
}
```

In the edit-indirect buffer it became like this:
```

      makeFlagsArray=(
        prefix="$out/share"
        ORG_ADD_CONTRIB="org* ox*"
        GITVERSION=
```

It seems to be an issue with the `${` in particular.

**Comment by terlar** [comment]
Tried the same in `python-mode` and that didn't have the same issue...

**Comment by twlz0ne** [comment]
`M-: (nth 3 (syntax-ppss))` returned nil on `${` means the cursor is not on a string, it seems an issue of `nix-mode`.

**Comment by terlar** [comment]
Wow you are my hero! I have not tested this yet, but if it works, it is truly going to improve my coding experience a lot. I am doing a lot of nix and this package feature is especially useful for nix as you frequently work with other languages within strings. Thank you 😀

**Comment by twlz0ne** [comment]
I realized that I only tested the example given in https://github.com/NixOS/nix-mode/issues/96 :

        "hello ${interpolated} wold"

The examples in this post are more complex, I'll  check them tomorrow during the day, it's already 2am here😴

**Comment by twlz0ne** [comment]
Now it is basically available unless you place the cursor between two strings:

```
{ key1="value1";| key2="value2"; }      -->     value1";| key2="value2
```
